/**
 * Auto-generated by scripts/generate-event-gallery.mjs — do not edit manually.
 * Re-run: npm run generate:gallery
 */
export const eventGalleryItems = [
  {
    "id": "weddings-whatsapp-image-2019-08-17-at-1-42-25-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202019-08-17%20at%201.42.25%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 1",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2019-08-17-at-1-46-45-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202019-08-17%20at%201.46.45%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 2",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2019-08-17-at-1-46-51-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202019-08-17%20at%201.46.51%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 3",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2019-08-17-at-1-47-40-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202019-08-17%20at%201.47.40%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 4",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2019-08-17-at-1-47-49-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202019-08-17%20at%201.47.49%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 5",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-58-59-pm-1",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.58.59%20PM%20(1).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 6",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-58-59-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.58.59%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 7",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-00-pm-1",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.00%20PM%20(1).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 8",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-00-pm-2",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.00%20PM%20(2).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 9",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-00-pm-3",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.00%20PM%20(3).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 10",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-00-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.00%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 11",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-01-pm-1",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.01%20PM%20(1).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 12",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-01-pm-2",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.01%20PM%20(2).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 13",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-01-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.01%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 14",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-12-pm-1",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.12%20PM%20(1).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 15",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-13-pm-1",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.13%20PM%20(1).jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 16",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-13-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.13%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 17",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "weddings-whatsapp-image-2026-09-13-at-11-59-14-pm",
    "src": "/images/gallery/Wedding%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.14%20PM.jpeg",
    "type": "image",
    "category": "weddings",
    "alt": "Khidmat Wedding Celebrations — photograph 18",
    "caption": "Wedding Celebrations",
    "title": "Wedding Celebrations"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-13-at-11-58-59-pm",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-13%20at%2011.58.59%20PM.jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 1",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-40-pm-1",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.40%20PM%20(1).jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 2",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-40-pm",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.40%20PM.jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 3",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-42-pm-1",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.42%20PM%20(1).jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 4",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-44-pm-1",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.44%20PM%20(1).jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 5",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-44-pm-2",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.44%20PM%20(2).jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 6",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-44-pm-3",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.44%20PM%20(3).jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 7",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-44-pm",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.44%20PM.jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 8",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-3-54-45-pm",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%203.54.45%20PM.jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 9",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "celebrations-whatsapp-image-2026-09-14-at-4-02-27-pm",
    "src": "/images/gallery/Birthday%20and%20other%20celebrations/WhatsApp%20Image%202026-09-14%20at%204.02.27%20PM.jpeg",
    "type": "image",
    "category": "celebrations",
    "alt": "Khidmat Celebrations and Special Occasions — photograph 10",
    "caption": "Celebrations & Special Occasions",
    "title": "Celebrations & Special Occasions"
  },
  {
    "id": "private-gatherings-image",
    "src": "/images/gallery/private%20gathering/image.png",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 1",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "private-gatherings-image1",
    "src": "/images/gallery/private%20gathering/image1.png",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 2",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "private-gatherings-whatsapp-image-2019-08-17-at-1-46-52-pm-1",
    "src": "/images/gallery/private%20gathering/WhatsApp%20Image%202019-08-17%20at%201.46.52%20PM%20(1).jpeg",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 3",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "private-gatherings-whatsapp-image-2019-08-17-at-1-46-53-pm",
    "src": "/images/gallery/private%20gathering/WhatsApp%20Image%202019-08-17%20at%201.46.53%20PM.jpeg",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 4",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "private-gatherings-whatsapp-image-2019-08-17-at-1-46-55-pm",
    "src": "/images/gallery/private%20gathering/WhatsApp%20Image%202019-08-17%20at%201.46.55%20PM.jpeg",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 5",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "private-gatherings-whatsapp-image-2026-09-14-at-3-54-41-pm-1",
    "src": "/images/gallery/private%20gathering/WhatsApp%20Image%202026-09-14%20at%203.54.41%20PM%20(1).jpeg",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 6",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "private-gatherings-whatsapp-image-2026-09-14-at-3-54-41-pm",
    "src": "/images/gallery/private%20gathering/WhatsApp%20Image%202026-09-14%20at%203.54.41%20PM.jpeg",
    "type": "image",
    "category": "private-gatherings",
    "alt": "Khidmat Private Gatherings — photograph 7",
    "caption": "Private Gatherings",
    "title": "Private Gatherings"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-35-14-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.35.14%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 1",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-40-21-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.40.21%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 2",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-42-18-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.42.18%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 3",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-47-42-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.47.42%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 4",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-47-43-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.47.43%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 5",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-47-44-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.47.44%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 6",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-47-47-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.47.47%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 7",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-47-50-pm-1",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.47.50%20PM%20(1).jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 8",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2019-08-17-at-1-47-51-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202019-08-17%20at%201.47.51%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 9",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-13-at-11-58-55-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-13%20at%2011.58.55%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 10",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-13-at-11-58-59-pm-1",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-13%20at%2011.58.59%20PM%20(1).jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 11",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-13-at-11-59-12-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-13%20at%2011.59.12%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 12",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-3-54-43-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%203.54.43%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 13",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-3-54-45-pm-1",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%203.54.45%20PM%20(1).jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 14",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-02-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.02%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 15",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-04-pm-1",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.04%20PM%20(1).jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 16",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-04-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.04%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 17",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-05-pm-1",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.05%20PM%20(1).jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 18",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-05-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.05%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 19",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-09-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.09%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 20",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-14-pm-1",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.14%20PM%20(1).jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 21",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-image-2026-09-14-at-4-02-28-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Image%202026-09-14%20at%204.02.28%20PM.jpeg",
    "type": "image",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — photograph 22",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-video-2026-09-14-at-3-54-46-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Video%202026-09-14%20at%203.54.46%20PM.mp4",
    "type": "video",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — video 1",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "food-setups-whatsapp-video-2026-09-14-at-4-02-03-pm",
    "src": "/images/gallery/food%20and%20set%20up/WhatsApp%20Video%202026-09-14%20at%204.02.03%20PM.mp4",
    "type": "video",
    "category": "food-setups",
    "alt": "Khidmat Food and Catering Setups — video 2",
    "caption": "Food & Catering Setups",
    "title": "Food & Catering Setups"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-02-pm-1",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.02%20PM%20(1).jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 1",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-02-pm-2",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.02%20PM%20(2).jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 2",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-02-pm",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.02%20PM.jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 3",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-03-pm-1",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.03%20PM%20(1).jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 4",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-03-pm-2",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.03%20PM%20(2).jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 5",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-03-pm-3",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.03%20PM%20(3).jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 6",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-03-pm",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.03%20PM.jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 7",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-04-pm",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.04%20PM.jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 8",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "school-events-whatsapp-image-2026-09-13-at-11-59-09-pm",
    "src": "/images/gallery/School%20catering/WhatsApp%20Image%202026-09-13%20at%2011.59.09%20PM.jpeg",
    "type": "image",
    "category": "school-events",
    "alt": "Khidmat School and Institutional Events — photograph 9",
    "caption": "School & Institutional Events",
    "title": "School & Institutional Events"
  },
  {
    "id": "team-whatsapp-image-2026-09-14-at-3-54-42-pm",
    "src": "/images/gallery/Our%20team/WhatsApp%20Image%202026-09-14%20at%203.54.42%20PM.jpeg",
    "type": "image",
    "category": "team",
    "alt": "Khidmat The Khidmat Team — photograph 1",
    "caption": "The Khidmat Team",
    "title": "The Khidmat Team"
  },
  {
    "id": "team-whatsapp-image-2026-09-14-at-3-54-43-pm-1",
    "src": "/images/gallery/Our%20team/WhatsApp%20Image%202026-09-14%20at%203.54.43%20PM%20(1).jpeg",
    "type": "image",
    "category": "team",
    "alt": "Khidmat The Khidmat Team — photograph 2",
    "caption": "The Khidmat Team",
    "title": "The Khidmat Team"
  },
  {
    "id": "team-whatsapp-image-2026-09-14-at-4-02-14-pm",
    "src": "/images/gallery/Our%20team/WhatsApp%20Image%202026-09-14%20at%204.02.14%20PM.jpeg",
    "type": "image",
    "category": "team",
    "alt": "Khidmat The Khidmat Team — photograph 3",
    "caption": "The Khidmat Team",
    "title": "The Khidmat Team"
  },
  {
    "id": "team-whatsapp-image-2026-09-14-at-4-02-26-pm",
    "src": "/images/gallery/Our%20team/WhatsApp%20Image%202026-09-14%20at%204.02.26%20PM.jpeg",
    "type": "image",
    "category": "team",
    "alt": "Khidmat The Khidmat Team — photograph 4",
    "caption": "The Khidmat Team",
    "title": "The Khidmat Team"
  },
  {
    "id": "team-whatsapp-image-2026-09-14-at-9-22-04-am-1",
    "src": "/images/gallery/Our%20team/WhatsApp%20Image%202026-09-14%20at%209.22.04%20AM%20(1).jpeg",
    "type": "image",
    "category": "team",
    "alt": "Khidmat The Khidmat Team — photograph 5",
    "caption": "The Khidmat Team",
    "title": "The Khidmat Team"
  },
  {
    "id": "team-whatsapp-image-2026-09-14-at-9-22-04-am",
    "src": "/images/gallery/Our%20team/WhatsApp%20Image%202026-09-14%20at%209.22.04%20AM.jpeg",
    "type": "image",
    "category": "team",
    "alt": "Khidmat The Khidmat Team — photograph 6",
    "caption": "The Khidmat Team",
    "title": "The Khidmat Team"
  }
];
